version: '3.8'

services:
  app:
    container_name: 'receipt-pdf-datastore'
    image: ${image}
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ../
    env_file:
      - ./.env
    ports:
      - "60486:80"
