apiVersion: v2
name: pagopareceiptpdfnotifier
description: Microservice description
type: application
version: 0.118.0
appVersion: 0.15.5-1-receipts-index-performance-test
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
